### ISSUE TITLE
malloc issue on snow leopard (10.6.2)

### ISSUE THREAD

**Issue by prb** [AndyA/htop-osx#1]
Build runs fine, but alas `htop` does not.

<pre>
htop(11589) malloc: *** error for object 0x100cf0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap
</pre>

**Comment by kfigiela** [comment]
Do this before ./configure:
export CFLAGS="-m32"

This will force building htop as x86 (32-bit, 64-bit by default) application - this way it works :)

**Comment by bitboxer** [comment]
That didn't work for me. I got : 

ld: symbol(s) not found
collect2: ld returned 1 exit status
make[1]: **\* [htop] Error 1
make: **\* [all] Error 2

as result of make

If you want to get the whole text, I can send that to you via mail.

**Comment by bitboxer** [comment]
Using MacPort I was able to build it. The PortFile:

http://trac.macports.org/browser/trunk/dports/sysutils/htop/Portfile

**Comment by kornea** [comment]
I didn't want to install macport (why installing another PERL dist to install htop), so I try to use your source. I have the same problem : 

htop(20786) malloc: **\* error for object 0x100df0: pointer being freed was not allocated
**\* set a breakpoint in malloc_error_break to debug
Abort trap

with snow 10.6.5. I try the CFLAGS tricks, but I still have the malloc error. 

Any fixes ?

regards

**Comment by klynch** [comment]
I'm on Snow Leopard 10.6.6 and compiling with CFLAGS="-m32" works for me and also with CFLAGS="-m32 -O2".

**Comment by nbigaouette** [comment]
On snow leopard 10.6.7 (Darwin 10.7.0), the following worked:
export CFLAGS="-m32" && ./autogen.sh && ./configure && make clean && make

**Comment by omellette** [comment]
On snow leopard 10.6.7, and the previous comment worked well. Thanks nbigaouette!

**Comment by ghost** [comment]
The above step to build from source and use CFLAGS does not work on yosemite. Please help

**Comment by JohnDDuncanIII** [comment]
@bansalgagan works for me on OS X 10.11.2 Beta 4
