### ISSUE TITLE
htop fails to execute on 10.7.2

### ISSUE THREAD

**Issue by m4rkw** [AndyA/htop-osx#6]
Hi,

Just compiled the osx branch on a 10.7.2 system and I get:
# ./htop

htop(28036) malloc: **\* error for object 0x9201240: pointer being freed was not allocated
**\* set a breakpoint in malloc_error_break to debug
Abort trap: 6

The macports version works but it seems to be just binaries and I want to hack some of the code so I can have a simple terminal readout of individual cpu core usage which will then be piped into Cacti.

Thanks,
Mark

**Comment by m4rkw** [comment]
found the answer: https://trac.macports.org/changeset/56880

**Comment by j0hnsmith** [comment]
I have this problem in 10.7. I'm trying to compile from source and don't understand what to do with that changeset.
